name: Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coveralls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts' # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.0
