
name: Tag Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build
      - run: make ci
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            mongogrator-linux-arm64.tar.gz
            mongogrator-linux.tar.gz
            mongogrator-mac.tar.gz
            mongogrator-mac-arm64.tar.gz
            mongogrator-windows.zip
            mongogrator-installer.sh
